<!--
  This file defines globally overridden top level and transitive packages for all projects in the solution 
  when known issues arise within those packages.

  This should be considered dynamic and projects listed may always be removed along with those being added.
-->
<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>
</Project>
