services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfiles/ui/Dockerfile.local
      args:
        OKTA_ISSUER: "https://identity-preview.inl.gov"
        NEXTAUTH_URL: "http://localhost:3000"
        REDIRECT_LINK: "http://localhost:3000/api/auth/callback/okta"
        NEXT_PUBLIC_DOCS_PATH: "http://localhost:3001/docs"
        NEXT_PUBLIC_API_URL: "http://localhost:5000/api/v1"
        OKTA_CLIENT_ID: ""
        OKTA_CLIENT_SECRET: ""
        NEXTAUTH_SECRET: "changeMe"
        BACKEND_BASE_URL: "http://server:5000/api/v1"
        AUTH_TRUST_HOST: true
        NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION: true # change to false if supplying okta info on lines 12-13, 25-26
    environment:
      NODE_ENV: production
      OKTA_ISSUER: "https://identity-preview.inl.gov"
      NEXTAUTH_URL: "http://localhost:3000"
      REDIRECT_LINK: "http://localhost:3000/api/auth/callback/okta"
      NEXT_PUBLIC_DOCS_PATH: "http://localhost:3001/docs"
      NEXT_PUBLIC_API_URL: "http://localhost:5000/api/v1"
      OKTA_CLIENT_ID: ""
      OKTA_CLIENT_SECRET: ""
      NEXTAUTH_SECRET: "changeMe"
      BACKEND_BASE_URL: "http://server:5000/api/v1"
      AUTH_TRUST_HOST: true
      NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION: true # change to false if supplying okta info on lines 12-13, 25-26
    ports:
      - "3000:3000"
    networks:
      - nexus-network
    depends_on:
      - server

  docs:
    build:
      context: ./
      dockerfile: Dockerfiles/docs/Dockerfile.local
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    networks:
      - nexus-network
    depends_on:
      - server

  server:
    build:
      context: ./
      dockerfile: Dockerfiles/server/Dockerfile.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nexuscore
      POSTGRES_DB_NAME: deeplynx
      POSTGRES_DB_HOST: nx-postgres
      POSTGRES_PORT: 5432
      FILE_STORAGE_METHOD: filesystem # values can be filesystem, azure_object, and aws_s3
      STORAGE_DIRECTORY: /data
      RECOMMENDED_CHUNK_SIZE: 100000000
      AZURE_OBJECT_CONNECTION_STRING: azure-example-connection-string
      AWS_S3_CONNECTION_STRING: aws-example-connection-string
      JWT_SECRET_KEY: demo_ZGDcnDdkRjLcx1kty9lXzlZ9L2ywFv3rC/91I3Z6fLQ= # for your local backend and can be changed
      JWT_ISSUER: https://identity-preview.inl.gov
      JWT_AUDIENCE: https://identity-preview.inl.gov
      SMTP_SERVER: mailhost.inl.gov
      SMTP_PORT: 25
      SMTP_ENABLE_SSL: false
      FROM_EMAIL: no-reply@inl.gov
      FROM_NAME: DeepLynx Nexus
      INVITE_URL: http://localhost:3000
      SUPPORT_EMAIL: jaren.brownlee@inl.gov
      DISABLE_BACKEND_AUTHENTICATION: true # change to false if supplying okta info on lines 12-13, 25-26
      SUPERUSER_EMAIL: jaren.brownlee@inl.gov

    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - "5000:5000"
    networks:
      - nexus-network
    volumes:
      - object_storage:/data
    depends_on:
        - nx-postgres

  nx-postgres:
    build:
      context: ./
      dockerfile: Dockerfiles/database/Dockerfile.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nexuscore
    ports:
      - "5432"
    networks:
      - nexus-network
    volumes:
      - nx_postgres_data:/var/lib/postgresql/data
    
  mcp:
    build:
      context: ./
      dockerfile: Dockerfiles/mcp/Dockerfile.local
    environment:
      NEXUS_API_URL: "http://server:5000/api/v1"
      MCP_SERVER_URL: "http://0.0.0.0:43656"
    ports:
      - "43656:43656"
    networks:
      - nexus-network
    depends_on:
      - server

networks:
  nexus-network:
    driver: bridge
  
volumes:
  object_storage:
    driver: local
  nx_postgres_data:
    driver: local