using System.Security.Cryptography;
using Microsoft.AspNetCore.DataProtection;

namespace deeplynx.helpers;

/// <summary>
/// Provides methods for generating and checking direct record URLs.
/// </summary>
public class RecordUrlHelper
{
    public const string DownloadProtector = "DownloadProtector";

    /// <summary>
    /// Generates a generic download URL that may be used to download a record file for any file business type.
    /// </summary>
    /// <param name="protector">Data protector to use for token creation. Should be unique for downloading</param>
    /// <param name="storage">Object storage type used for storing the record file</param>
    /// <param name="downloadUrl">Generic download URL to supply the token into</param>
    /// <param name="recordId">Record to be downloaded</param>
    /// <param name="uri">Record's path in the particulat file business</param>
    /// <param name="expirationHours">Hours before the token expires</param>
    /// <returns>direct URL to download the record with token authentication</returns>
    public static string GenerateGenericDownloadUrl(ITimeLimitedDataProtector protector, string storage, string? downloadUrl, long recordId, string uri, int expirationHours)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(storage, "Object Storage Type");
        ArgumentException.ThrowIfNullOrWhiteSpace(uri, "Record URI");
        ArgumentException.ThrowIfNullOrWhiteSpace(downloadUrl, "Download URL");

        var hours = new TimeSpan(hours: expirationHours, minutes: 0, seconds: 0);
        var payload = $"{recordId}:{storage}";
        var token = protector.Protect(payload, hours);
        return $"{downloadUrl}?token={token}";
    }

    /// <summary>
    /// Validates a download token and retrieves the object storage type used for storing the record
    /// </summary>
    /// <param name="protector">Data protector that generated the original token</param>
    /// <param name="token">Token generated by the data protector</param>
    /// <param name="expectedRecordId">Expected record ID to be found in the token</param>
    /// <returns>object storage type if the download token is valid and null otherwise</returns>
    public static string? ValidateObjectStorageType(ITimeLimitedDataProtector protector, string token, long expectedRecordId)
    {
        try
        {
            var payload = protector.Unprotect(token).Split(":");

            var recordId = long.Parse(payload[0]);
            if (recordId != expectedRecordId) return null; // expect record

            var storage = payload[1];
            return storage; // find storage type
        }
        catch (CryptographicException)
        {
            return null; // tampered or wrong key
        }
        catch (Exception)
        {
            return null; // expired or malformed
        }
    }
}
