# Stage 1: Build the frontend
FROM node:22-alpine AS frontend-build

# Define build arguments
ARG OKTA_ISSUER
ARG NEXTAUTH_URL
ARG REDIRECT_LINK
ARG NEXT_PUBLIC_DOCS_PATH
ARG NEXT_PUBLIC_API_URL
ARG OKTA_CLIENT_ID
ARG OKTA_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG BACKEND_BASE_URL
ARG NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION
ARG AUTH_TRUST_HOST

# Set environment variables
ENV OKTA_ISSUER=${OKTA_ISSUER}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV REDIRECT_LINK=${REDIRECT_LINK}
ENV NEXT_PUBLIC_DOCS_PATH=${NEXT_PUBLIC_DOCS_PATH}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
ENV OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV BACKEND_BASE_URL=${BACKEND_BASE_URL}
ENV AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
ENV NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION=${NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION}

# Set working directory
WORKDIR /usr/src/app

# Configure INL certs and environment variables
RUN apk --no-check-certificate add wget ca-certificates
RUN wget -q -P /usr/local/share/ca-certificates/ http://certstore.inl.gov/pki/CAINLROOT_B64.crt
RUN /usr/sbin/update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs/

# Copy dependency metadata first for better cache reuse
COPY deeplynx.UI/package.json deeplynx.UI/package-lock.json ./

# Install frontend dependencies
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy the rest of the frontend source code
COPY deeplynx.UI ./

# Build the frontend
RUN npm run build

# Stage 2: Create the final image
FROM node:22-alpine AS final

# Set working directory
WORKDIR /usr/src/app

# Copy standalone runtime output and 
USER root
COPY --from=frontend-build /usr/src/app/.next/standalone ./
COPY --from=frontend-build /usr/src/app/.next/static ./.next/static
COPY --from=frontend-build /usr/src/app/public ./public

# Allow runtime cache in case of dhi perm blocking
RUN mkdir -p /usr/src/app/.next/cache \
    && chown -R node:node /usr/src/app

# Expose the port the app runs on
EXPOSE 3000

# Set the command to run the application
CMD ["node", "server.js"]