// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deeplynx.datalayer.Models;

#nullable disable

namespace deeplynx.datalayer.Migrations.Lattice
{
    [DbContext(typeof(LatticeContext))]
    [Migration("20260504162924_AddValidationColumns")]
    partial class AddValidationColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lattice")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("OntologyClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("ontology_class_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("PromotedId")
                        .HasColumnType("bigint")
                        .HasColumnName("promoted_id");

                    b.Property<string>("ValidationStatus")
                        .HasColumnType("text")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.ToTable("extraction_classes", "lattice");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long>("DestinationRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_record_id");

                    b.Property<double>("EmbeddingPlausibility")
                        .HasColumnType("double precision")
                        .HasColumnName("embedding_plausibility");

                    b.Property<double>("EnsembleScore")
                        .HasColumnType("double precision")
                        .HasColumnName("ensemble_score");

                    b.Property<long>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<long>("ExtractionRelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_relationship_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<double>("LlmScore")
                        .HasColumnType("double precision")
                        .HasColumnName("llm_score");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("OriginRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_record_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("PromotedId")
                        .HasColumnType("bigint")
                        .HasColumnName("promoted_id");

                    b.Property<double>("StatisticalFrequency")
                        .HasColumnType("double precision")
                        .HasColumnName("statistical_frequency");

                    b.Property<double>("StructuralConsistency")
                        .HasColumnType("double precision")
                        .HasColumnName("structural_consistency");

                    b.Property<string>("ValidationStatus")
                        .HasColumnType("text")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("DestinationRecordId");

                    b.HasIndex("ExtractionRelationshipId");

                    b.HasIndex("OriginRecordId");

                    b.ToTable("extraction_edges", "lattice");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long?>("DeeplynxRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("deeplynx_record_id");

                    b.Property<double>("EmbeddingPlausibility")
                        .HasColumnType("double precision")
                        .HasColumnName("embedding_plausibility");

                    b.Property<double>("EnsembleScore")
                        .HasColumnType("double precision")
                        .HasColumnName("ensemble_score");

                    b.Property<long>("ExtractionClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_class_id");

                    b.Property<long>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<double>("LlmScore")
                        .HasColumnType("double precision")
                        .HasColumnName("llm_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("PromotedId")
                        .HasColumnType("bigint")
                        .HasColumnName("promoted_id");

                    b.Property<double>("StatisticalFrequency")
                        .HasColumnType("double precision")
                        .HasColumnName("statistical_frequency");

                    b.Property<double>("StructuralConsistency")
                        .HasColumnType("double precision")
                        .HasColumnName("structural_consistency");

                    b.Property<string>("ValidationStatus")
                        .HasColumnType("text")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionClassId");

                    b.ToTable("extraction_records", "lattice");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DestinationClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_class_id");

                    b.Property<long>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("OntologyRelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("ontology_relationship_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("OriginClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_class_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("PromotedId")
                        .HasColumnType("bigint")
                        .HasColumnName("promoted_id");

                    b.Property<string>("ValidationStatus")
                        .HasColumnType("text")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("DestinationClassId");

                    b.HasIndex("OriginClassId");

                    b.ToTable("extraction_relationships", "lattice");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionEdge", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.ExtractionRecord", "DestinationRecord")
                        .WithMany("DestinationEdges")
                        .HasForeignKey("DestinationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extraction_edges_destination_record_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.ExtractionRelationship", "ExtractionRelationship")
                        .WithMany("Edges")
                        .HasForeignKey("ExtractionRelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extraction_edges_extraction_relationship_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.ExtractionRecord", "OriginRecord")
                        .WithMany("OriginEdges")
                        .HasForeignKey("OriginRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extraction_edges_origin_record_id_fkey");

                    b.Navigation("DestinationRecord");

                    b.Navigation("ExtractionRelationship");

                    b.Navigation("OriginRecord");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionRecord", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.ExtractionClass", "ExtractionClass")
                        .WithMany("Records")
                        .HasForeignKey("ExtractionClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extraction_records_extraction_class_id_fkey");

                    b.Navigation("ExtractionClass");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionRelationship", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.ExtractionClass", "DestinationClass")
                        .WithMany("DestinationRelationships")
                        .HasForeignKey("DestinationClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extraction_relationships_destination_class_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.ExtractionClass", "OriginClass")
                        .WithMany("OriginRelationships")
                        .HasForeignKey("OriginClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extraction_relationships_origin_class_id_fkey");

                    b.Navigation("DestinationClass");

                    b.Navigation("OriginClass");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionClass", b =>
                {
                    b.Navigation("DestinationRelationships");

                    b.Navigation("OriginRelationships");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionRecord", b =>
                {
                    b.Navigation("DestinationEdges");

                    b.Navigation("OriginEdges");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ExtractionRelationship", b =>
                {
                    b.Navigation("Edges");
                });
#pragma warning restore 612, 618
        }
    }
}
