# Stage 1: Build the frontend
FROM node:lts-alpine3.23 AS frontend-build

# Set working directory
WORKDIR /usr/src/app

# Install versioned os packages
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache \
    busybox

# Install latest global npm version and packages
RUN npm install -g npm@latest

# Copy package.json first
COPY deeplynx.docs/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend source code
COPY deeplynx.docs .

# Build the frontend
RUN npm run build

# Stage 2: Create the final image
FROM node:lts-alpine3.23 AS final

# Set working directory
WORKDIR /usr/src/app

# Install versioned os packages
RUN apk update && apk upgrade --no-cache && \
    apk add --no-cache \
    busybox

# Install latest global npm version and packages
RUN npm install -g npm@latest

# Copy the built frontend code from the previous stage
COPY --from=frontend-build /usr/src/app .

# Install production dependencies
RUN npm install --omit=dev

# Explicitly set user
RUN addgroup -S nexus && adduser -S nexus -G nexus
RUN chown -R nexus:nexus /usr/src/app
USER nexus

# Expose the port the app runs on
EXPOSE 3001

# Set the command to run the application
CMD ["npm", "start"]
