# Stage 1: Build the frontend
FROM node:lts-alpine AS frontend-build

# Set working directory
WORKDIR /usr/src/app

# Configure INL certs and environment variables
RUN apk --no-check-certificate add wget ca-certificates
RUN wget -q -P /usr/local/share/ca-certificates/ http://certstore.inl.gov/pki/CAINLROOT_B64.crt
RUN /usr/sbin/update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs/

# Copy dependency metadata first
COPY deeplynx.docs/package.json deeplynx.docs/package-lock.json ./

# Install frontend dependencies
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy the rest of the frontend source code
COPY deeplynx.docs ./

# Build the frontend
RUN npm run build

# Stage 2: Create the final image
FROM node:lts-alpine AS final

# Set working directory
WORKDIR /usr/src/app

# Configure INL certs and environment variables
RUN apk --no-check-certificate add wget ca-certificates
RUN wget -q -P /usr/local/share/ca-certificates/ http://certstore.inl.gov/pki/CAINLROOT_B64.crt
RUN /usr/sbin/update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs/

# Copy dependency metadata first
COPY deeplynx.docs/package.json deeplynx.docs/package-lock.json ./

# Install production dependencies
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev

# Copy the built frontend code from the previous stage
COPY --from=frontend-build /usr/src/app ./

# Expose the port the app runs on
EXPOSE 3001

# Set the command to run the application
CMD ["npm", "start" ]