# Stage 1: Build the C# backend
FROM mcr.microsoft.com/dotnet/sdk:10.0.202 AS backend-build

# Set working directory
WORKDIR /usr/src/app

# Copy the solution file and restore dependencies
COPY deeplynx.sln .
COPY deeplynx.api ./deeplynx.api
COPY deeplynx.business ./deeplynx.business
COPY deeplynx.datalayer ./deeplynx.datalayer
COPY deeplynx.helpers ./deeplynx.helpers
COPY deeplynx.interfaces ./deeplynx.interfaces
COPY deeplynx.models ./deeplynx.models
COPY deeplynx.tests ./deeplynx.tests
RUN dotnet restore deeplynx.sln

# Build the backend
RUN dotnet build deeplynx.sln -c Release -o /app/build

# Publish the backend
FROM backend-build AS publish
RUN dotnet publish deeplynx.sln -c Release -o /app/publish /p:UseAppHost=false

# Stage 2: Create the final image
FROM mcr.microsoft.com/dotnet/aspnet:10.0.9 AS final

# Set working directory
WORKDIR /usr/src/app

# Fix vulnerability
RUN apt-get update && \
    apt-get install -y libgnutls30t64=3.8.3-1.1ubuntu3.6 && \
    rm -rf /var/lib/apt/lists/*

# Copy the published backend code
COPY --from=publish /app/publish .

# Copy additional files if needed
COPY deeplynx.api/moon.css ./moon.css

# Explicitly set user
RUN groupadd -r nexus && useradd -r -g nexus -m -s /usr/sbin/nologin nexus
RUN chown -R nexus:nexus /usr/src/app
USER nexus

# This will run the .NET application directly
CMD ["dotnet", "deeplynx.api.dll", "--urls", "http://*:5000"]