// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deeplynx.datalayer.Models;

#nullable disable

namespace deeplynx.datalayer.Migrations.Staging
{
    [DbContext(typeof(StagingContext))]
    [Migration("20260413204828_AddFileSizeColumn")]
    partial class AddFileSizeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("staging")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("GroupId", "UserId");

                    b.ToTable("GroupUser", "staging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("PermissionId", "RoleId");

                    b.ToTable("PermissionRole", "staging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RecordSensitivityLabel", b =>
                {
                    b.Property<long>("LabelId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.HasKey("LabelId", "RecordId");

                    b.ToTable("RecordSensitivityLabel", "staging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RecordTag", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("RecordId", "TagId");

                    b.ToTable("RecordTag", "staging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex("ExtractionId")
                        .HasDatabaseName("idx_classes_extraction_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_classes_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_classes_name");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("idx_classes_organization_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_classes_project_id");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("idx_classes_uuid");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("unique_organization_class_name")
                        .HasFilter("project_id IS NULL");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("unique_class_name");

                    b.HasIndex("OrganizationId", "ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("unique_project_class_name")
                        .HasFilter("project_id IS NOT NULL");

                    b.ToTable("classes", "staging");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.CrossSchemaEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DeeplynxDestinationOriginalId")
                        .HasColumnType("text")
                        .HasColumnName("deeplynx_destination_original_id");

                    b.Property<string>("DeeplynxOriginOriginalId")
                        .HasColumnType("text")
                        .HasColumnName("deeplynx_origin_original_id");

                    b.Property<string>("DeeplynxRelationshipName")
                        .HasColumnType("text")
                        .HasColumnName("deeplynx_relationship_name");

                    b.Property<string>("DestinationOriginalId")
                        .HasColumnType("text")
                        .HasColumnName("destination_original_id");

                    b.Property<long>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated_by");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginOriginalId")
                        .HasColumnType("text")
                        .HasColumnName("origin_original_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("RelationshipName")
                        .HasColumnType("text")
                        .HasColumnName("relationship_name");

                    b.HasKey("Id")
                        .HasName("cross_schema_edges_pkey");

                    b.HasIndex("ExtractionId")
                        .HasDatabaseName("idx_cross_schema_edges_extraction_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_cross_schema_edges_project_id");

                    b.ToTable("cross_schema_edges", "staging");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<long?>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated_by");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<long?>("RelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.HasKey("Id")
                        .HasName("edges_pkey");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("idx_edges_data_source_id");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("idx_edges_destination_id");

                    b.HasIndex("ExtractionId")
                        .HasDatabaseName("idx_edges_extraction_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_edges_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("idx_edges_organization_id");

                    b.HasIndex("OriginId")
                        .HasDatabaseName("idx_edges_origin_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_edges_project_id");

                    b.HasIndex("RelationshipId")
                        .HasDatabaseName("idx_edges_relationship_id");

                    b.HasIndex("ProjectId", "OriginId", "DestinationId")
                        .IsUnique()
                        .HasDatabaseName("unique_edge_record_ids");

                    b.ToTable("edges", "staging", t =>
                        {
                            t.HasCheckConstraint("CK_edges_origin_destination_different", "origin_id <> destination_id");
                        });
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Extraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.HasKey("Id");

                    b.ToTable("extractions", "deeplynx", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<string>("ClassName")
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Embedded")
                        .HasColumnType("boolean")
                        .HasColumnName("embedded");

                    b.Property<long?>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ObjectStorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_storage_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("records_pkey");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("idx_records_class_id");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("idx_records_data_source_id");

                    b.HasIndex("ExtractionId")
                        .HasDatabaseName("idx_records_extraction_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_records_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_records_name");

                    b.HasIndex("ObjectStorageId")
                        .HasDatabaseName("idx_records_object_storage_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("idx_records_organization_id");

                    b.HasIndex("OriginalId")
                        .HasDatabaseName("idx_records_original_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_records_project_id");

                    b.HasIndex("ProjectId", "DataSourceId", "OriginalId")
                        .IsUnique()
                        .HasDatabaseName("unique_record_original_id");

                    b.HasIndex(new[] { "Properties" }, "idx_records_properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Properties" }, "idx_records_properties"), "gin");

                    b.ToTable("records", "staging");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<string>("DestinationName")
                        .HasColumnType("text")
                        .HasColumnName("destination_name");

                    b.Property<long?>("ExtractionId")
                        .HasColumnType("bigint")
                        .HasColumnName("extraction_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long?>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<string>("OriginName")
                        .HasColumnType("text")
                        .HasColumnName("origin_name");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("relationships_pkey");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("idx_relationships_destination_id");

                    b.HasIndex("ExtractionId")
                        .HasDatabaseName("idx_relationships_extraction_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_relationships_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_relationships_name");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("idx_relationships_organization_id");

                    b.HasIndex("OriginId")
                        .HasDatabaseName("idx_relationships_origin_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_relationships_project_id");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("idx_relationships_uuid");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("unique_organization_relationship_name")
                        .HasFilter("project_id IS NULL");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("unique_relationship_name");

                    b.HasIndex("OrganizationId", "ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("unique_project_relationship_name")
                        .HasFilter("project_id IS NOT NULL");

                    b.ToTable("relationships", "staging");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Extraction", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("classes_extraction_id_fkey");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.CrossSchemaEdge", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Extraction", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cross_schema_edges_extraction_id_fkey");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Record", "Destination")
                        .WithMany("EdgeDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Extraction", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("edges_extraction_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Record", "Origin")
                        .WithMany("EdgeOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Relationship", "Relationship")
                        .WithMany("Edges")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("edges_relationship_id_fkey");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Class")
                        .WithMany("Records")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("records_class_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Extraction", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("records_extraction_id_fkey");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Destination")
                        .WithMany("RelationshipDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("relationships_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Extraction", null)
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("relationships_extraction_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Class", "Origin")
                        .WithMany("RelationshipOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("relationships_origin_id_fkey");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.Navigation("Records");

                    b.Navigation("RelationshipDestinations");

                    b.Navigation("RelationshipOrigins");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.Navigation("EdgeDestinations");

                    b.Navigation("EdgeOrigins");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.Navigation("Edges");
                });
#pragma warning restore 612, 618
        }
    }
}
