name: Preflight Build Check

on:
  workflow_dispatch:
  pull_request:
    branches: ["develop", "main"]

jobs:
  build-check:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build Test
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
        run: |
          cd $GITHUB_WORKSPACE
          az cloud set --name AzureUSGovernment
          az login --service-principal -u $ACR_SP_USER -p $ACR_SP_PASSWORD --tenant $ACR_SP_TENANT
          az account set --subscription $ACR_SUBSCRIPTION
          az acr build --registry $ACR_REGISTRY \
            --image $ACR_PATH:deeplynxv3-ui-$GITHUB_RUN_NUMBER \
            --file Dockerfiles/ui/Dockerfile.public \
            --build-arg OKTA_CLIENT_ID=${{ vars.OKTA_CLIENT_ID }} \
            --build-arg OKTA_ISSUER=${{ vars.OKTA_ISSUER }} \
            --build-arg NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} \
            --build-arg REDIRECT_LINK=${{ vars.REDIRECT_LINK }} \
            --build-arg OKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg SERVICE_TOKEN=${{ secrets.SERVICE_TOKEN }} \
            --build-arg BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }} \
            --build-arg NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION=${{ vars.NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION }} \
            .

          az acr build --registry $ACR_REGISTRY \
            --image $ACR_PATH:deeplynxv3-server-$GITHUB_RUN_NUMBER \
            --file Dockerfiles/server/Dockerfile.public \
            --build-arg OKTA_CLIENT_ID=${{ vars.OKTA_CLIENT_ID }} \
            --build-arg OKTA_ISSUER=${{ vars.OKTA_ISSUER }} \
            --build-arg NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} \
            --build-arg REDIRECT_LINK=${{ vars.REDIRECT_LINK }} \
            --build-arg OKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }} \
            --build-arg SERVICE_TOKEN=${{ secrets.SERVICE_TOKEN }} \
            --build-arg NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION=${{ vars.NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION }} \
            --build-arg HOSTED_LINK=${{ vars.HOSTED_LINK }} \
            .

          echo "✅ Both Docker images built successfully!"

#  run-dotnet-tests:
#    runs-on: [self-hosted]
#    needs: build-check
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Build and Run .NET Tests in Docker Container
#        env:
#          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
#          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
#          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
#          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
#          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
#        run: |
#          cd $GITHUB_WORKSPACE
#          az cloud set --name AzureUSGovernment
#          az login --service-principal -u $ACR_SP_USER -p $ACR_SP_PASSWORD --tenant $ACR_SP_TENANT
#          az account set --subscription $ACR_SUBSCRIPTION
#
#          # Build backend image and run tests
#          az acr build --registry $ACR_REGISTRY \
#            --file Dockerfiles/server/Dockerfile.testing \
#            --image backend-image:latest \
#            .
#
#          echo "✅ .NET tests ran successfully in Docker container!"
