name: Build Sandbox/Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "Test"

  push:
    branches: ["develop"]

jobs:
  build-ui:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
          OKTA_CLIENT_ID: ${{ vars.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          OKTA_ISSUER: ${{ vars.OKTA_ISSUER }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          REDIRECT_LINK: ${{ vars.REDIRECT_LINK }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
          BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
          NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION: ${{ vars.NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry "$ACR_REGISTRY" \
            --image "$ACR_PATH:deeplynx-ui-${{ github.run_number }}" \
            --file Dockerfiles/ui/Dockerfile.public \
            --build-arg OKTA_CLIENT_ID="$OKTA_CLIENT_ID" \
            --build-arg OKTA_ISSUER="$OKTA_ISSUER" \
            --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
            --build-arg REDIRECT_LINK="$REDIRECT_LINK" \
            --build-arg OKTA_CLIENT_SECRET="$OKTA_CLIENT_SECRET" \
            --build-arg JWT_SECRET_KEY="$JWT_SECRET_KEY" \
            --build-arg AUTH_SECRET="$AUTH_SECRET" \
            --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
            --build-arg SERVICE_TOKEN="$SERVICE_TOKEN" \
            --build-arg BACKEND_BASE_URL="$BACKEND_BASE_URL" \
            --build-arg NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION=$NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION \
            .

  build-server:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
          OKTA_CLIENT_ID: ${{ vars.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          OKTA_ISSUER: ${{ vars.OKTA_ISSUER }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          REDIRECT_LINK: ${{ vars.REDIRECT_LINK }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
          BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
          NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION: ${{ vars.NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION }}
          HOSTED_LINK: ${{ vars.HOSTED_LINK }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry "$ACR_REGISTRY" \
            --image "$ACR_PATH:deeplynx-server-${{ github.run_number }}" \
            --file Dockerfiles/server/Dockerfile.public \
            --build-arg OKTA_CLIENT_ID="$OKTA_CLIENT_ID" \
            --build-arg OKTA_ISSUER="$OKTA_ISSUER" \
            --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
            --build-arg REDIRECT_LINK="$REDIRECT_LINK" \
            --build-arg OKTA_CLIENT_SECRET="$OKTA_CLIENT_SECRET" \
            --build-arg JWT_SECRET_KEY="$JWT_SECRET_KEY" \
            --build-arg AUTH_SECRET="$AUTH_SECRET" \
            --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
            --build-arg BACKEND_BASE_URL="$BACKEND_BASE_URL" \
            --build-arg SERVICE_TOKEN="$SERVICE_TOKEN" \
            --build-arg NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION=$NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION \
            --build-arg HOSTED_LINK="$HOSTED_LINK" \
            .

  build-docs:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
          HOSTED_LINK: ${{ vars.HOSTED_LINK }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry "$ACR_REGISTRY" \
            --image "$ACR_PATH:deeplynx-docs-${{ github.run_number }}" \
            --file Dockerfiles/docs/Dockerfile.public \
            --build-arg HOSTED_LINK="$HOSTED_LINK" \
            .

  build-mcp:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry $ACR_REGISTRY \
            --image $ACR_PATH:deeplynx-mcp-$GITHUB_RUN_NUMBER \
            --file Dockerfiles/mcp/Dockerfile.public \
            .

  build-insight-rabbitmq:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - name: Checkout Insight Submodule
        env:
          INSIGHT_KEY: ${{ secrets.DEPLOY_KEY_INSIGHT }}
          KNOWN_HOSTS: ${{ secrets.GHE_KNOWN_HOSTS }}
        run: |
          echo "$INSIGHT_KEY" > /tmp/insight_deploy
          echo "$KNOWN_HOSTS" > /tmp/known_hosts
          chmod 600 /tmp/insight_deploy
          GIT_SSH_COMMAND="ssh -i /tmp/insight_deploy -o UserKnownHostsFile=/tmp/known_hosts" git submodule update --init --recursive deeplynx.insight
          rm /tmp/insight_deploy /tmp/known_hosts
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry $ACR_REGISTRY \
            --image $ACR_PATH:insight-rabbitmq-$GITHUB_RUN_NUMBER \
            --file deeplynx.insight/Dockerfiles/Dockerfile.rabbitmq.production \
            deeplynx.insight

  build-insight-rabbitmq-runner:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - name: Checkout Insight Submodule
        env:
          INSIGHT_KEY: ${{ secrets.DEPLOY_KEY_INSIGHT }}
          KNOWN_HOSTS: ${{ secrets.GHE_KNOWN_HOSTS }}
        run: |
          echo "$INSIGHT_KEY" > /tmp/insight_deploy
          echo "$KNOWN_HOSTS" > /tmp/known_hosts
          chmod 600 /tmp/insight_deploy
          GIT_SSH_COMMAND="ssh -i /tmp/insight_deploy -o UserKnownHostsFile=/tmp/known_hosts" git submodule update --init --recursive deeplynx.insight
          rm /tmp/insight_deploy /tmp/known_hosts
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry $ACR_REGISTRY \
            --image $ACR_PATH:insight-rabbitmq-runner-$GITHUB_RUN_NUMBER \
            --file deeplynx.insight/Dockerfiles/Dockerfile.runner.production \
            deeplynx.insight

  build-insight-fastapi:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ secrets.GHE_KNOWN_HOSTS }}
      - name: Checkout Insight Submodule
        env:
          INSIGHT_KEY: ${{ secrets.DEPLOY_KEY_INSIGHT }}
          KNOWN_HOSTS: ${{ secrets.GHE_KNOWN_HOSTS }}
        run: |
          echo "$INSIGHT_KEY" > /tmp/insight_deploy
          echo "$KNOWN_HOSTS" > /tmp/known_hosts
          chmod 600 /tmp/insight_deploy
          GIT_SSH_COMMAND="ssh -i /tmp/insight_deploy -o UserKnownHostsFile=/tmp/known_hosts" git submodule update --init --recursive deeplynx.insight
          rm /tmp/insight_deploy /tmp/known_hosts
      - shell: bash
        name: Container Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
        run: |
          az cloud set --name AzureUSGovernment
          az login --service-principal -u "$ACR_SP_USER" -p "$ACR_SP_PASSWORD" --tenant "$ACR_SP_TENANT"
          az account set --subscription "$ACR_SUBSCRIPTION"
          az acr build --registry $ACR_REGISTRY \
            --image $ACR_PATH:insight-fastapi-$GITHUB_RUN_NUMBER \
            --file deeplynx.insight/Dockerfiles/Dockerfile.fastapi.production \
            deeplynx.insight

  kubernetes:
    needs:
      [
        build-ui,
        build-server,
        build-docs,
        build-mcp,
        build-insight-rabbitmq,
        build-insight-rabbitmq-runner,
        build-insight-fastapi,
      ]
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3

      - uses: azure/k8s-set-context@v3
        name: Configure K8s
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DE_DEV }}
          context: deploy-service-account

      - shell: bash
        name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=okta-client-secret="${{ secrets.OKTA_CLIENT_SECRET }}" \
            --from-literal=auth-secret="${{ secrets.AUTH_SECRET }}" \
            --from-literal=next-auth-secret="${{ secrets.NEXTAUTH_SECRET }}" \
            --from-literal=service-token="${{ secrets.SERVICE_TOKEN }}" \
            --from-literal=jwt-secret-key="${{ secrets.JWT_SECRET_KEY }}" \
            --from-literal=rabbitmq-default-pass="${{ secrets.RABBITMQ_DEFAULT_PASS }}" \
            --from-literal=llm-auth-token="${{ secrets.LLM_AUTH_TOKEN }}" \
            --from-literal=mm-auth-token="${{ secrets.MM_AUTH_TOKEN }}" \
            --from-literal=emb-auth-token="${{ secrets.EMB_AUTH_TOKEN }}" \
            --from-literal=encryption-key="${{ secrets.ENCRYPTION_KEY }}" \
            --from-literal=encryption-iv="${{ secrets.ENCRYPTION_IV }}" \
            --namespace=deeplynx-test \
            --dry-run=client -o yaml | kubectl apply -f -

      - shell: bash
        name: Create Kubernetes ConfigMap
        run: |
          kubectl create configmap app-config \
            --from-literal=okta-client-id="${{ vars.OKTA_CLIENT_ID }}" \
            --from-literal=okta-issuer="${{ vars.OKTA_ISSUER }}" \
            --from-literal=auth-url="${{ vars.NEXTAUTH_URL }}" \
            --from-literal=redirect-link="${{ vars.REDIRECT_LINK }}" \
            --from-literal=backend-base-url="${{ vars.BACKEND_BASE_URL }}" \
            --from-literal=disabled-front-auth="${{ vars.NEXT_PUBLIC_DISABLE_FRONTEND_AUTHENTICATION }}" \
            --from-literal=hosted-link="${{ vars.HOSTED_LINK }}" \
            --from-literal=rabbitmq-default-user="${{ vars.RABBITMQ_DEFAULT_USER }}" \
            --namespace=deeplynx-test \
            --dry-run=client -o yaml | kubectl apply -f -

      - shell: bash
        name: Manifest env substitute
        env:
          AWS_S3_CONNECTION_STRING: ${{ secrets.AWS_S3_CONNECTION_STRING }}
          AZURE_OBJECT_CONNECTION_STRING: ${{ secrets.AZURE_OBJECT_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_ACCOUNT_SAS_TOKEN }}
          AZURE_FILE_SHARE_VOLUME_HANDLE: ${{ vars.AZURE_FILE_SHARE_VOLUME_HANDLE }}
          AZURE_FILE_SHARE_STORAGE_CLASS: ${{ vars.AZURE_FILE_SHARE_STORAGE_CLASS }}
          AZURE_FILE_SHARE_PERSISTENT_VOLUME: ${{ vars.AZURE_FILE_SHARE_PERSISTENT_VOLUME }}
          AZURE_FILE_SHARE_PVC: ${{ vars.AZURE_FILE_SHARE_PVC }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_RESOURCE_GROUP: ${{ vars.AZURE_ACCOUNT_RESOURCE_GROUP }}
          AZURE_CONTAINER_NAME: ${{ vars.AZURE_CONTAINER_NAME }}
          FROM_NAME: ${{vars.FROM_NAME}}
          FROM_EMAIL: ${{vars.FROM_EMAIL}}
          SUPPORT_EMAIL: ${{vars.SUPPORT_EMAIL}}
          SMTP_ENABLE_SSL: ${{vars.SMTP_ENABLE_SSL}}
          SMTP_PORT: ${{vars.SMTP_PORT}}
          INVITE_URL: ${{vars.INVITE_URL}}
          SMTP_SERVER: ${{vars.SMTP_SERVER}}
          CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
          CI_REGISTRY_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
          FILE_STORAGE_METHOD: ${{ vars.FILE_STORAGE_METHOD }}
          DUCKDB_BASE_PATH: ${{ vars.DUCKDB_BASE_PATH }}
          STORAGE_DIRECTORY: ${{ vars.STORAGE_DIRECTORY }}
          RECOMMENDED_CHUNK_SIZE: ${{ vars.RECOMMENDED_CHUNK_SIZE }}
          POSTGRES_DB_HOST: ${{ vars.POSTGRES_DB_HOST }}
          POSTGRES_DB_NAME: ${{ vars.POSTGRES_DB_NAME }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          JWT_ISSUER: ${{vars.JWT_ISSUER}}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_AUDIENCE: ${{vars.JWT_AUDIENCE}}
          INSIGHT_FASTAPI_URL: ${{ vars.INSIGHT_FASTAPI_URL }}
          ENCRYPTION_KEY: ${{ vars.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ vars.ENCRYPTION_IV }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          AIRFLOW_BASE_URL: ${{ vars.AIRFLOW_BASE_URL }}
          AIRFLOW_USERNAME: ${{ vars.AIRFLOW_USERNAME }}
          AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
          LATTICE_MODEL: ${{ vars.LATTICE_MODEL }}
          NEXUS_API_URL: ${{ vars.NEXUS_API_URL }}
        run: |
          cd $GITHUB_WORKSPACE/kubernetes
          envsubst < sandbox.yaml > manifest.yaml

      - uses: Azure/k8s-deploy@v4
        name: Deploy K8s Workload
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          name: ${{ secrets.AKS_CLUSTER_NAME }}
          namespace: deeplynx-test
          action: deploy
          force: true
          strategy: basic
          manifests: |
            kubernetes/manifest.yaml
